### ISSUE TITLE
Missing ReportsController for Solidus 2.8.0

### ISSUE THREAD

**Issue by Ethan-Rivas** [2beDigital/solidus_simple_reports#1]
Hi!,

After I used this command `rails g solidus_simple_reports:install` this error appeared:

```
gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant': uninitialized constant Spree::Admin::ReportsController (NameError)
```

I solved this error adding the `solidus_reports` gem (plugin) to my project.
I think this gem was working with the latest version, which had this gem by default, but now in version 2.8.0, they removed it from the backend and [moved it as an extension](https://github.com/solidusio/solidus/pull/2814).

**Comment by NoelDiazMesa** [comment]
This gem is prepared for versions prior to 2.8, in version 2.8 of solidus have removed the reports from the core. Please install https://github.com/solidusio-contrib/solidus_reports before this gem and try again

**Comment by NoelDiazMesa** [comment]
sorry, you are right
